# Analysis options for Iman Flow
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_single_quotes: true
    avoid_print: true
    prefer_final_locals: true
    sort_constructors_first: true
    avoid_unnecessary_containers: true
    prefer_const_literals_to_create_immutables: true
