// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwYUdpEUMK8_UgFhiNHQ-1IfiX1DRZGfA',
    appId: '1:504848553840:web:2f8de98e2330077f4861b5',
    messagingSenderId: '504848553840',
    projectId: 'esas-67202',
    authDomain: 'esas-67202.firebaseapp.com',
    storageBucket: 'esas-67202.firebasestorage.app',
    measurementId: 'G-KVZHHFETTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc-erPTsP28-5bUKy6GRhwWPKVGdaZd1k',
    appId: '1:504848553840:android:3a77090c0ea4dfcc4861b5',
    messagingSenderId: '504848553840',
    projectId: 'esas-67202',
    storageBucket: 'esas-67202.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWE-01lCEMmHcZqzdGFe8L9-a6E3jerT4',
    appId: '1:504848553840:ios:677778ff6fb8e5ce4861b5',
    messagingSenderId: '504848553840',
    projectId: 'esas-67202',
    storageBucket: 'esas-67202.firebasestorage.app',
    iosBundleId: 'com.imanflow.imanFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWE-01lCEMmHcZqzdGFe8L9-a6E3jerT4',
    appId: '1:504848553840:ios:be55c928c5e68cc64861b5',
    messagingSenderId: '504848553840',
    projectId: 'esas-67202',
    storageBucket: 'esas-67202.firebasestorage.app',
    iosBundleId: 'com.example.imanFlow',
  );
}
